object Versions {
    const val playServicesVersion = "21.2.0"
    const val firebaseBom = "33.1.2"
    const val coil = "2.6.0"
    const val gson = "2.11.0"
    const val hiltNavigation = "1.1.0"
    const val compose = "1.5.0"
    const val composeBom = "2023.08.00"
    const val composeMaterial3 = "1.1.1"
    const val composeCompiler = "1.5.1"
    const val activityCompose = "1.9.0"
    const val hilt = "2.48"
    const val okHttp = "5.0.0-alpha.2"
    const val retrofit = "2.9.0"
    const val room = "2.5.0"
    const val splashScreen = "1.0.0"
    const val lifecycle = "2.8.2"
    const val navigation = "2.7.7"
    const val javaPoet = "1.13.0"
    const val kotlin = "1.9.0"
    const val xSerialization = "1.6.0"
}